function(add_target_compile_options binary_name)
    if (${vendor} STREQUAL "STM32")
        message("-- Adding compiler options: STM32")
    elseif (${vendor} STREQUAL "X86")
        message("-- Adding compiler options: X86")
    else ()
        message(FATAL_ERROR, "-- Adding compiler options: Unsupported vendor: ${vendor}")
    endif()
endfunction()