set(CMAKE_SYSTEM_NAME       AVR)
set(CMAKE_SYSTEM_VERSION    1)
set(CMAKE_SYSTEM_PROCESSOR  avr)
set(CMAKE_C_COMPILER_WORKS  1)

set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${CMAKE_CURRENT_LIST_DIR}/Modules" CACHE STRING "CMAKE modules")

find_package(AvrToolchain REQUIRED)
find_package(${mcu_family} REQUIRED)
