function(generate_binary target_name vendor)
    message(STATUS "Configuring binary tool ${target_name}: ${vendor}")
    if (${vendor} STREQUAL "STM32")
        include (stm32/GenerateStm32Binary)
        generate_stm32_binary(${target_name})
    elseif (${vendor} STREQUAL "ATMEL")
        include (avr/GenerateAvrBinary)
        generate_avr_binary(${target_name})
    else ()
        include (StubGenerateBinary)
    endif ()
endfunction()
